package br.com.msscsh.isoutil.enumeradores.elo;

import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_001_BITMAP;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_002_NUMERO_DO_CARTAO;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_003_CODIGO_PROCESSAMENTO;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_004_AMOUNT_TRANSACTION;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_005_AMOUNT_SETTLEMENT;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_006_AMOUNT_CARDHOLDER_BILLING;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_007_TRANSMISSION_DATE_TIME;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_008_AMOUNT_CARDHOLDER_BILLING_FEE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_009_CONVERSION_RATE_SETTLEMENT;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_010_CONVERSION_RATE_CARDHOLDER_BILLING;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_011_SYSTEM_TRACE_AUDIT_NUMBER_STAN;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_012_LOCAL_TRANSACTION_TIME_HHMMSS;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_013_LOCAL_TRANSACTION_DATE_MMDD;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_014_EXPIRATION_DATE_YYMM;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_015_SETTLEMENT_DATE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_016_CURRENCY_CONVERSION_DATE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_018_MERCHANT_TYPE_OR_MERCHANT_CATEGORY_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_019_ACQUIRING_INSTITUTION_COUNTRY_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_022_POINT_OF_SERVICE_ENTRY_MODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_023_APPLICATION_PAN_SEQUENCE_NUMBER;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_024_FUNCTION_CODE_ISO_8583_1993_OR_NETWORK_INTERNATIONAL_IDENTIFIER_NII;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_025_POINT_OF_SERVICE_CONDITION_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_026_POINT_OF_SERVICE_CAPTURE_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_028_AMOUNT_TRANSACTION_FEE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_029_AMOUNT_SETTLEMENT_FEE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_032_ACQUIRING_INSTITUTION_IDENTIFICATION_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_033_FORWARDING_INSTITUTION_IDENTIFICATION_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_035_TRACK_2_DATA;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_036_TRACK_3_DATA;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_037_RETRIEVAL_REFERENCE_NUMBER;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_038_AUTHORIZATION_IDENTIFICATION_RESPONSE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_039_RESPONSE_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_041_CARD_ACCEPTOR_TERMINAL_IDENTIFICATION;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_042_CARD_ACCEPTOR_IDENTIFICATION_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_043_CARD_ACCEPTOR_NAME_LOCATION;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_045_TRACK_1_DATA;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_046_ADDITIONAL_DATA_ISO;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_047_ADDITIONAL_DATA_NATIONAL;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_048_ADDITIONAL_DATA_PRIVATE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_049_CURRENCY_CODE_TRANSACTION;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_050_CURRENCY_CODE_SETTLEMENT;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_051_CURRENCY_CODE_CARDHOLDER_BILLING;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_052_PERSONAL_IDENTIFICATION_NUMBER_DATA;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_053_SECURITY_RELATED_CONTROL_INFORMATION;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_054_ADDITIONAL_AMOUNTS;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_055_ICC_DATA_EMV_HAVING_MULTIPLE_TAGS;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_056_RESERVED_ISO;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_058_RESERVED_NATIONAL;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_059_RESERVED_NATIONAL;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_060_RESERVED_NATIONAL;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_062_RESERVED_PRIVATE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_063_RESERVED_PRIVATE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_070_NETWORK_MANAGEMENT_INFORMATION_CODE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_090_ORIGINAL_DATA_ELEMENTS;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_095_REPLACEMENT_AMOUNTS;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_100_BITMAP;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_104_TRANSACTION_DESCRIPTION;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_105_RESERVED_FOR_ISO_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_106_RESERVED_FOR_ISO_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_107_RESERVED_FOR_ISO_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_121_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_122_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_123_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_124_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_125_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_126_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.BIT_127_RESERVED_FOR_PRIVATE_USE;
import static br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL.IDENTIFICADO_DO_TIPO_DE_MENSAGEM;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import br.com.msscsh.isoutil.enumeradores.ParteMensagemCOBOL;
import lombok.AllArgsConstructor;

/**
 *
 * Com inutito de agrupar as parte da mensagem, com seus dados que podem variar
 *
 */
@AllArgsConstructor
public enum DeParaCOBOLCopybookCampoElo {

//IDENTIFICADO_DO_TIPO_DE_MENSAGEM
    BIT0_IDTM(IDENTIFICADO_DO_TIPO_DE_MENSAGEM.getNumeroDaParte(), "ASZLO015-IDTM", 1, 4, 0),

    BIT1_MAPA_BIT_EXTENDIDO(BIT_001_BITMAP.getNumeroDaParte(), "MAPA-BIT-EXT", 1, 192, 0),
    BIT1_MAPA_BITS_PRIMARIO(BIT_001_BITMAP.getNumeroDaParte(), "MAPA-BITS-PRIMARIO", 2, 16, 0),
    BIT1_MAPA_BITS_SECUNDARIO(BIT_001_BITMAP.getNumeroDaParte(), "MAPA-BITS-SECUNDARIO", 3, 16, 0),

    BIT2_LONG_TJT_PAN_NU(BIT_002_NUMERO_DO_CARTAO.getNumeroDaParte(), "LONG-TJT-PAN-NU", 1, 2, 0),
    BIT2_TJT_PAN_NU(BIT_002_NUMERO_DO_CARTAO.getNumeroDaParte(), "TJT-PAN-NU", 2, 19, 0),

    BIT3_CODPRC_PREST(BIT_003_CODIGO_PROCESSAMENTO.getNumeroDaParte(), "CODPRC-PREST", 1, 1, 0),
    BIT3_CODPRC_12(BIT_003_CODIGO_PROCESSAMENTO.getNumeroDaParte(), "CODPRC-12", 2, 2, 0),
    BIT3_CODPRC_34(BIT_003_CODIGO_PROCESSAMENTO.getNumeroDaParte(), "CODPRC-34", 3, 2, 0),
    BIT3_CODPRC_56(BIT_003_CODIGO_PROCESSAMENTO.getNumeroDaParte(), "CODPRC-56", 4, 2, 0),

    BIT4_IMPORTE_PREST(BIT_004_AMOUNT_TRANSACTION.getNumeroDaParte(), "IMPORTE-PREST", 1, 1, 0),
    BIT4_IMPORTE(BIT_004_AMOUNT_TRANSACTION.getNumeroDaParte(), "IMPORTE", 2, 12, 0),

    BIT5_IMP_MOE_LIQ_PREST(BIT_005_AMOUNT_SETTLEMENT.getNumeroDaParte(), "IMP-MOE-LIQ-PREST", 1, 1, 0),
    BIT5_IMP_MOE_LIQ(BIT_005_AMOUNT_SETTLEMENT.getNumeroDaParte(), "IMP-MOE-LIQ", 2, 12, 0),

    BIT6_IMP_MOE_EMIS_PREST(BIT_006_AMOUNT_CARDHOLDER_BILLING.getNumeroDaParte(), "IMP-MOE-EMIS-PREST", 1, 1, 0),
    BIT6_IMP_MOE_EMIS(BIT_006_AMOUNT_CARDHOLDER_BILLING.getNumeroDaParte(), "IMP-MOE-EMIS", 2, 12, 0),

    BIT7_FEC_TRANS(BIT_007_TRANSMISSION_DATE_TIME.getNumeroDaParte(), "FEC-TRANS", 1, 4, 0),
    BIT7_HOR_TRANS(BIT_007_TRANSMISSION_DATE_TIME.getNumeroDaParte(), "HOR-TRANS", 2, 6, 0),

    BIT8_IMP_MOE_PORT_DEC(BIT_008_AMOUNT_CARDHOLDER_BILLING_FEE.getNumeroDaParte(), "IMP-MOE-PORT-DEC", 1, 1, 0),
    BIT8_IMP_MOE_PORT(BIT_008_AMOUNT_CARDHOLDER_BILLING_FEE.getNumeroDaParte(), "IMP-MOE-PORT", 2, 7, 0),

    BIT9_TAX_MOE_LIQ_DEC(BIT_009_CONVERSION_RATE_SETTLEMENT.getNumeroDaParte(), "TAX-MOE-LIQ-DEC", 1, 1, 0),
    BIT9_TAX_MOE_LIQ(BIT_009_CONVERSION_RATE_SETTLEMENT.getNumeroDaParte(), "TAX-MOE-LIQ", 2, 7, 0),
    BIT9_TAX_MOE_LIQ_DEC2(BIT_009_CONVERSION_RATE_SETTLEMENT.getNumeroDaParte(), "TAX-MOE-LIQ-DEC", 3, 1, 0),
    BIT9_TAX_MOE_LIQ2(BIT_009_CONVERSION_RATE_SETTLEMENT.getNumeroDaParte(), "TAX-MOE-LIQ", 4, 7, 0),

    BIT10_TAX_MOE_PORT_DEC(BIT_010_CONVERSION_RATE_CARDHOLDER_BILLING.getNumeroDaParte(), "TAX-MOE-PORT-DEC", 1, 1, 0),
    BIT10_TAX_MOE_PORT(BIT_010_CONVERSION_RATE_CARDHOLDER_BILLING.getNumeroDaParte(), "TAX-MOE-PORT", 2, 7, 0),
    BIT10_TAX_MOE_PORT_DEC2(BIT_010_CONVERSION_RATE_CARDHOLDER_BILLING.getNumeroDaParte(), "TAX-MOE-PORT-DEC", 3, 1, 0),
    BIT10_TAX_MOE_PORT2(BIT_010_CONVERSION_RATE_CARDHOLDER_BILLING.getNumeroDaParte(), "TAX-MOE-PORT", 4, 7, 0),

    BIT11_IDETRANS(BIT_011_SYSTEM_TRACE_AUDIT_NUMBER_STAN.getNumeroDaParte(), "IDETRANS", 1, 6, 0),

    BIT12_HOPEORI(BIT_012_LOCAL_TRANSACTION_TIME_HHMMSS.getNumeroDaParte(), "HOPEORI", 1, 6, 0),

    BIT13_FOPEORI(BIT_013_LOCAL_TRANSACTION_DATE_MMDD.getNumeroDaParte(), "FOPEORI", 1, 4, 0),

    BIT14_FCADUCID(BIT_014_EXPIRATION_DATE_YYMM.getNumeroDaParte(), "FCADUCID", 1, 4, 0),

    BIT15_DATA_LIQUIDA(BIT_015_SETTLEMENT_DATE.getNumeroDaParte(), "DATA-LIQUIDA", 1, 4, 0),

    BIT16_DATA_CONVER(BIT_016_CURRENCY_CONVERSION_DATE.getNumeroDaParte(), "DATA_CONVER", 1, 4, 0),

    BIT18_CODACT_EST(BIT_018_MERCHANT_TYPE_OR_MERCHANT_CATEGORY_CODE.getNumeroDaParte(), "CODACT-EST", 1, 4, 0),

    BIT19_COD_PAIS_ADQ(BIT_019_ACQUIRING_INSTITUTION_COUNTRY_CODE.getNumeroDaParte(), "CODACT-EST", 1, 3, 0),

    BIT22_PNT_SERV_PREST(BIT_022_POINT_OF_SERVICE_ENTRY_MODE.getNumeroDaParte(), "PNT-SERV-PREST", 1, 1, 0),
    BIT22_DAT_PNT_SERV(BIT_022_POINT_OF_SERVICE_ENTRY_MODE.getNumeroDaParte(), "DAT_PNT_SERV", 2, 3, 0),
    BIT22_MODO_ENT_PAN(BIT_022_POINT_OF_SERVICE_ENTRY_MODE.getNumeroDaParte(), "MODO-ENT-PAN", 3, 3, 0),
    BIT22_MOD_ENT_PAN(BIT_022_POINT_OF_SERVICE_ENTRY_MODE.getNumeroDaParte(), "MOD-ENT-PAN", 4, 3, 0),
    BIT22_MODO_ENT_PIN(BIT_022_POINT_OF_SERVICE_ENTRY_MODE.getNumeroDaParte(), "MODO-ENT-PIN", 5, 1, 0),

    BIT23_NUMTAR(BIT_023_APPLICATION_PAN_SEQUENCE_NUMBER.getNumeroDaParte(), "NUMTAR", 1, 3, 0),

    BIT24_COD_FUNCAO(BIT_024_FUNCTION_CODE_ISO_8583_1993_OR_NETWORK_INTERNATIONAL_IDENTIFIER_NII.getNumeroDaParte(),
	    "COD-FUNCAO", 1, 3, 0),

    BIT25_COD_MOTIV_MSG_PREST(BIT_025_POINT_OF_SERVICE_CONDITION_CODE.getNumeroDaParte(), "COD-MOTIV-MSG-PREST", 1, 1,
	    0),
    BIT25_COD_MOTIV_MSG(BIT_025_POINT_OF_SERVICE_CONDITION_CODE.getNumeroDaParte(), "COD-MOTIV-MSG", 2, 2, 0),

    BIT26_COD_CAPT_PIN_PREST(BIT_026_POINT_OF_SERVICE_CAPTURE_CODE.getNumeroDaParte(), "COD-CAPT-PIN-PREST", 1, 1, 0),
    BIT26_COD_CAPT_PIN(BIT_026_POINT_OF_SERVICE_CAPTURE_CODE.getNumeroDaParte(), "COD-CAPT-PIN", 2, 2, 0),

    BIT28_VAL_TAXA_TRN_PREST(BIT_028_AMOUNT_TRANSACTION_FEE.getNumeroDaParte(), "VAL-TAXA-TRN-PREST", 1, 1, 0),
    BIT28_TIPO_TAXA_TRN(BIT_028_AMOUNT_TRANSACTION_FEE.getNumeroDaParte(), "TIPO-TAXA-TRN", 2, 1, 0),
    BIT28_VAL_TAXA_TRN(BIT_028_AMOUNT_TRANSACTION_FEE.getNumeroDaParte(), "VAL-TAXA-TRN", 3, 8, 0),

    BIT29_VAL_TAXA_LIQ_PREST(BIT_029_AMOUNT_SETTLEMENT_FEE.getNumeroDaParte(), "VAL-TAXA-LIQ-PREST", 1, 1, 0),
    BIT29_TIPO_TAXA_LIQ(BIT_029_AMOUNT_SETTLEMENT_FEE.getNumeroDaParte(), "VAL-TAXA-LIQ-PREST", 2, 1, 0),
    BIT29_VAL_TAXA_LIQ(BIT_029_AMOUNT_SETTLEMENT_FEE.getNumeroDaParte(), "VAL-TAXA-LIQ", 3, 8, 0),

    BIT32_LONG_IDENADQ(BIT_032_ACQUIRING_INSTITUTION_IDENTIFICATION_CODE.getNumeroDaParte(), "LONG-IDENADQ", 1, 2, 0),
    BIT32_IDENADQ(BIT_032_ACQUIRING_INSTITUTION_IDENTIFICATION_CODE.getNumeroDaParte(), "IDENADQ", 2, 11, 0),

    BIT33_LONG_IDENREPA(BIT_033_FORWARDING_INSTITUTION_IDENTIFICATION_CODE.getNumeroDaParte(), "LONG-IDENREPA", 1, 2,
	    0),
    BIT33_IDENREPA(BIT_033_FORWARDING_INSTITUTION_IDENTIFICATION_CODE.getNumeroDaParte(), "IDENREPA", 2, 11, 0),

    BIT35_LONG_DAPISTA2(BIT_035_TRACK_2_DATA.getNumeroDaParte(), "LONG-DAPISTA2", 1, 2, 0),
    BIT35_DAPISTA2(BIT_035_TRACK_2_DATA.getNumeroDaParte(), "DAPISTA2", 2, 40, 0),

    BIT36_LONG_TRILHA3(BIT_036_TRACK_3_DATA.getNumeroDaParte(), "LONG-TRILHA3", 1, 2, 0),
    BIT36_TRILHA3(BIT_036_TRACK_3_DATA.getNumeroDaParte(), "TRILHA3", 2, 40, 0),

    BIT37_NUM_REF(BIT_037_RETRIEVAL_REFERENCE_NUMBER.getNumeroDaParte(), "NUM-REF", 1, 12, 0),

    BIT38_NUM_AUTORIZA(BIT_038_AUTHORIZATION_IDENTIFICATION_RESPONSE.getNumeroDaParte(), "NUM-AUTORIZA", 1, 6, 0),

    BIT39_CODACC(BIT_039_RESPONSE_CODE.getNumeroDaParte(), "CODACC", 1, 2, 0),

    BIT41_IDENT_TERM(BIT_041_CARD_ACCEPTOR_TERMINAL_IDENTIFICATION.getNumeroDaParte(), "IDENT_TERM", 1, 8, 0),

    BIT42_CODFUC(BIT_042_CARD_ACCEPTOR_IDENTIFICATION_CODE.getNumeroDaParte(), "CODFUC", 1, 15, 0),

    // BIT 43
    BIT43_NOMEDOESTABELECIMENTO(BIT_043_CARD_ACCEPTOR_NAME_LOCATION.getNumeroDaParte(), "NOMEDOESTABELECIMENTO", 1, 22,
	    1),
    BIT43_NOMEDACIDADE(BIT_043_CARD_ACCEPTOR_NAME_LOCATION.getNumeroDaParte(), "NOMEDACIDADE", 2, 13, 1),
    BIT43_CODIGODOPAISOUESTADO(BIT_043_CARD_ACCEPTOR_NAME_LOCATION.getNumeroDaParte(), "CODIGODOPAISOUESTADO", 3, 3, 0),

    BIT45_LONG_DAPISTA1(BIT_045_TRACK_1_DATA.getNumeroDaParte(), "LONG-DAPISTA1", 1, 2, 0),
    BIT45_DAPISTA1(BIT_045_TRACK_1_DATA.getNumeroDaParte(), "DAPISTA1", 2, 77, 0),

    BIT46_DADOS_ADI_RESP_LONG(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-RESP-LONG", 1, 3, 0),
    BIT46_DADOS_ADI_RESPOSTA(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-RESPOSTA", 2, 999, 0),
    BIT46_DADOS_ADI_TLF(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-TLF", 3, 25, 0),
    BIT46_DADOS_ADI_TLF_FILLER(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "FILLER", 4, 974, 0),
    BIT46_DADOS_ADI_AVS(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-AVS", 5, 1, 0),
    BIT46_DADOS_ADI_CVE2(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-CVE2", 6, 1, 0),
    BIT46_DADOS_ADI_FONT(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-FONT", 7, 1, 0),
    BIT46_DADOS_ADI_FLOO(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-FLOO", 8, 4, 0),
    BIT46_DADOS_ADI_ERRO(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-ERRO", 9, 3, 0),
    BIT46_DADOS_ADI_ERRO2(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS_ADI_ERRO2", 10, 3, 0),
    BIT46_DADOS_ADI_ACN(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-ACN", 11, 3, 0),
    BIT46_DADOS_ADI_CVV(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-CVV", 12, 1, 0),
    BIT46_DADOS_ADI_CRIP(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-CRIP", 13, 1, 0),
    BIT46_DADOS_ADI_TVR(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-TVR", 14, 1, 0),
    BIT46_DADOS_ADI_CVR(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-CVR", 15, 1, 0),
    BIT46_DADOS_ADI_NOME(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-ADI-NOME", 16, 1, 0),
    BIT46_DADOS_NUM_COB(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-NUM-COB", 17, 1, 0),
    BIT46_DADOS_NOM_COB(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-NOM-COB", 18, 1, 0),
    BIT46_DADOS_CID_COB(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-CID-COB", 19, 1, 0),
    BIT46_DADOS_UF_COB(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-UF-COB", 20, 1, 0),
    BIT46_DADOS_MAIL_COB(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-MAIL-COB", 21, 1, 0),
    BIT46_DADOS_ADI_COB1(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-MAIL-COB1", 22, 1, 0),
    BIT46_DADOS_ADI_COB2(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-MAIL-COB2", 23, 1, 0),
    BIT46_DADOS_ADI_COB3(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-MAIL-COB3", 24, 1, 0),
    BIT46_DADOS_PAD_COB(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "DADOS-PAD-COB", 25, 1, 0),
    BIT46_COD_RESP_CAVV(BIT_046_ADDITIONAL_DATA_ISO.getNumeroDaParte(), "COD-RESP-CAVV", 26, 1, 0),

    BIT47_DADOS_ADI_NACI_LONG(BIT_047_ADDITIONAL_DATA_NATIONAL.getNumeroDaParte(), "DADOS-ADI-NACI-LONG", 1, 3, 0),
    BIT47_DADOS_ADI_NACIONAIS(BIT_047_ADDITIONAL_DATA_NATIONAL.getNumeroDaParte(), "DADOS-ADI-NACIONAIS", 2, 999, 0),

    BIT48_LONG_DATPRIV(BIT_048_ADDITIONAL_DATA_PRIVATE.getNumeroDaParte(), "LONG-DATPRIV ", 1, 3, 0),
    BIT48_DATPRIV(BIT_048_ADDITIONAL_DATA_PRIVATE.getNumeroDaParte(), "DATPRIV ", 2, 999, 0),

    BIT49_COD_MON_TRANS(BIT_049_CURRENCY_CODE_TRANSACTION.getNumeroDaParte(), "COD-MON-TRANS ", 1, 3, 0),

    BIT50_COD_MON_LIQ(BIT_050_CURRENCY_CODE_SETTLEMENT.getNumeroDaParte(), "COD-MON-LIQ ", 1, 3, 0),

    BIT51_COD_MON_PORT(BIT_051_CURRENCY_CODE_CARDHOLDER_BILLING.getNumeroDaParte(), "COD-MON-PORT", 1, 3, 0),

    BIT52_PINBLOCK(BIT_052_PERSONAL_IDENTIFICATION_NUMBER_DATA.getNumeroDaParte(), "PINBLOCK", 1, 8, 0),

    BIT53_GES_SEGU_MSG(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-MSG", 1, 16, 0),
    BIT53_GES_SEGU_DET_POS1(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-DET-POS1", 2, 2,
	    0),
    BIT53_GES_SEGU_DET_POS2(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-DET-POS2", 3, 2,
	    0),
    BIT53_GES_SEGU_DET_POS3(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-DET-POS3", 4, 2,
	    0),
    BIT53_GES_SEGU_DET_POS4(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-DET-POS4", 5, 2,
	    0),
    BIT53_GES_SEGU_DET_POS5(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-DET-POS5", 6, 2,
	    0),
    BIT53_GES_SEGU_DET_POS6(BIT_053_SECURITY_RELATED_CONTROL_INFORMATION.getNumeroDaParte(), "GES-SEGU-DET-POS6", 7, 5,
	    0),

    BIT54_LONG_IMP_ADI(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "LONG-IMP-ADI", 1, 3, 0),
    BIT54_IMP_ADI(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMP-ADI", 2, 120, 0),
    BIT54_IMP_ADI2(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMP-ADI2", 3, 80, 0),
    BIT54_IMPADI_TIPCONTA(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMPADI-TIPCONTA", 4, 2, 0),
    BIT54_IMPADI_TIPVALOR(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMPADI-TIPVALOR", 5, 2, 0),
    BIT54_IMPADI_CODMOEDA(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMPADI-CODMOEDA", 6, 3, 0),
    BIT54_IMPADI_SIGNO(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMPADI-SIGNO", 7, 1, 0),
    BIT54_IMPADI_VALOR(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "IMPADI-VALOR", 8, 12, 0),
    BIT54_IMPADI_FILLER(BIT_054_ADDITIONAL_AMOUNTS.getNumeroDaParte(), "FILLER", 9, 60, 0),

    BIT55_LONG_DAT_CHIP(BIT_055_ICC_DATA_EMV_HAVING_MULTIPLE_TAGS.getNumeroDaParte(), "LONG-DAT-CHIP", 1, 3, 0),
    BIT55_DATOS_TJT_CHIP(BIT_055_ICC_DATA_EMV_HAVING_MULTIPLE_TAGS.getNumeroDaParte(), "DATOS-TJT-CHIP", 2, 999, 0),
    BIT55_DATOS_TJT_CHIP2(BIT_055_ICC_DATA_EMV_HAVING_MULTIPLE_TAGS.getNumeroDaParte(), "DATOS-TJT-CHIP2", 3, 255, 0),

    BIT56_LONG_DAD_CONSUM(BIT_056_RESERVED_ISO.getNumeroDaParte(), "LONG-DAD-CONSUM", 1, 3, 0),
    BIT56_LONG_REL_CONSUM(BIT_056_RESERVED_ISO.getNumeroDaParte(), "LONG-DAD-CONSUM", 2, 999, 0),

    BIT58_LONG_DAD_GEOGRA(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "LONG-DAD-GEOGRA", 1, 3, 0),
    BIT58_DADOS_GEOGRAF(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "DADOS-GEOGRAF", 2, 60, 0),
    BIT58_DADGEO_RUA(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "DADGEO-RUA", 3, 22, 0),
    BIT58_DADGEO_CEP(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "DADGEO-CEP", 4, 9, 0),
    BIT58_DADGEO_PAIS(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "DADGEO-PAIS", 5, 3, 0),
    BIT58_DADGEO_NUMLOJA(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "DADGEO-NUMLOJA", 6, 5, 0),
    BIT58_DADGEO_NOMSHOP(BIT_058_RESERVED_NATIONAL.getNumeroDaParte(), "DADGEO-NOMSHOP", 7, 21, 0),

    BIT59_LONG_DAD_TRANSP(BIT_059_RESERVED_NATIONAL.getNumeroDaParte(), "LONG-DAD-TRANSP", 1, 3, 0),
    BIT59_DADOS_TRANSPO(BIT_059_RESERVED_NATIONAL.getNumeroDaParte(), "DADOS-TRANSPO", 2, 100, 0),

    BIT60_LONG_POS_INFORM(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "LONG-POS-INFORM", 1, 3, 0),
    BIT60_TIPO_TERM(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "TIPO-TERM", 2, 1, 0),
    BIT60_CAPACIDAD_TERM(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "CAPACIDAD-TERM", 3, 1, 0),
    BIT60_COND_CHIP(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "COND-CHIP", 4, 1, 0),
    BIT60_ECOMMERCE(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "ECOMMERCE", 5, 2, 0),
    BIT60_TIPO_TERM2(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "TIPO-TERM2", 6, 1, 0),
    BIT60_IND_APROV_PARC(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-APROV-PARC", 7, 1, 0),
    BIT60_IND_LOCA_TERM(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-LOCA-TERM", 8, 1, 0),
    BIT60_IND_PRES_PORT(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-PRES-PORT", 9, 1, 0),
    BIT60_IND_PRES_CART(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-PRES-CART", 10, 1, 0),
    BIT60_IND_CAPT_CART(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-CAPT-CART", 11, 1, 0),
    BIT60_IND_STAT_TRAN(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-STAT-TRAN", 12, 1, 0),
    BIT60_IND_SEGU_TRAN(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-SEGU-TRAN", 13, 1, 0),
    BIT60_IND_RESERV1(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-RESERV1", 14, 1, 0),
    BIT60_TIPO_POS_TERM(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "TIPO-POS-TERM", 15, 1, 0),
    BIT60_CAPACI_TERM(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "CAPACI-TERM", 16, 1, 0),
    BIT60_IND_RESERV2(BIT_060_RESERVED_NATIONAL.getNumeroDaParte(), "IND-RESERV2", 17, 2, 0),

    BIT62_LONG_DAD_ONLINE(BIT_062_RESERVED_PRIVATE.getNumeroDaParte(), "LONG-DAD-ONLINE", 1, 3, 0),
    BIT62_DAD_ONLINE(BIT_062_RESERVED_PRIVATE.getNumeroDaParte(), "DAD-ONLINE", 2, 999, 0),

    BIT63_LONG_DADOS_AVS(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "LONG-DADOS-AVS", 1, 3, 0),
    BIT63_AVS_S1_CODPOS(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S1-CODPOS", 2, 9, 0),
    BIT63_AVS_S1_RUA(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S1-RUA", 3, 5, 0),
    BIT63_AVS_S1_NOME1(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S1-NOME1", 4, 35, 0),
    BIT63_AVS_S1_SOBREN(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S1-SOBREN", 5, 35, 0),
    BIT63_AVS_S2_NUMRUA(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-NUMRUA", 6, 15, 0),
    BIT63_AVS_S2_NOMRUA(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-NOMRUA", 7, 26, 0),
    BIT63_AVS_S2_CIDADE(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-CIDADE", 8, 18, 0),
    BIT63_AVS_S2_ESTADO(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-ESTADO", 9, 2, 0),
    BIT63_AVS_S2_EMAIL(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-EMAIL", 10, 64, 0),
    BIT63_AVS_S2_TELEF1(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-TELEF1", 11, 15, 0),
    BIT63_AVS_S2_TELEF2(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-TELEF2", 12, 15, 0),
    BIT63_AVS_S2_TELEF3(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-TELEF3", 13, 15, 0),
    BIT63_AVS_S2_ENDERE(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S2-ENDERE", 14, 1, 0),
    BIT63_AVS_S3_NOME1(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-NOME1", 15, 35, 0),
    BIT63_AVS_S3_SOBREN(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-SOBREN", 16, 35, 0),
    BIT63_AVS_S3_NUMRUA(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-NUMRUA", 17, 15, 0),
    BIT63_AVS_S3_NOMRUA(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-NOMRUA", 18, 26, 0),
    BIT63_AVS_S3_CIDADE(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-CIDADE", 19, 18, 0),
    BIT63_AVS_S3_ESTADO(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-ESTADO", 20, 2, 0),
    BIT63_AVS_S3_CODPOS(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-CODPOS", 21, 9, 0),
    BIT63_AVS_S3_PAIS(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-PAIS", 22, 3, 0),
    BIT63_AVS_S3_EMAIL(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-EMAIL", 23, 64, 0),
    BIT63_AVS_S3_TELEF1(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-TELEF1", 24, 15, 0),
    BIT63_AVS_S3_TELEF2(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-TELEF2", 25, 15, 0),
    BIT63_AVS_S3_TELEF3(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-TELEF3", 26, 15, 0),
    BIT63_AVS_S3_INDIP(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-INDIP", 27, 1, 0),
    BIT63_AVS_S3_IPV6(BIT_063_RESERVED_PRIVATE.getNumeroDaParte(), "AVS-S3-IPV6", 28, 39, 0),

    BIT70_CONTROL_DIALOGO(BIT_070_NETWORK_MANAGEMENT_INFORMATION_CODE.getNumeroDaParte(), "CONTROL-DIALOGO", 1, 3, 0),

    BIT90_IDTM_ORI(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDTM-ORI", 1, 4, 0),
    BIT90_NUMAUTORI_ORI(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "NUMAUTORI-ORI", 2, 6, 0),
    BIT90_NUMAUTORI_ORI2(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "NUMAUTORI-ORI2", 3, 6, 0),
    BIT90_FHOTRANS_ORI(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "FHOTRANS-ORI", 4, 10, 0),
    BIT90_IDETRANS_ORI(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDETRANS-ORI", 5, 6, 0),
    BIT90_IDETRANS_ORI2(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDETRANS-ORI2", 6, 6, 0),
    BIT90_DADOS_ORIGINAL(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "DADOS-ORIGINAL", 7, 42, 0),
    BIT90_IDTM_ORI_N(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDTM-ORI-N", 8, 4, 0),
    BIT90_IDETRANS_ORI_N(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDETRANS-ORI-N", 9, 6, 0),
    BIT90_DHOTRANS_ORI_N(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDETRANS-ORI-N", 10, 10, 0),
    BIT90_NUMAUTO_ORI_N(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "NUMAUTO-ORI-N", 11, 6, 0),
    BIT90_FILLER(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "BIT90_FILLER", 12, 16, 0),
    BIT90_IDTM_ORI_I(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDTM-ORI-I", 13, 4, 0),
    BIT90_IDETRANS_ORI_I(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "IDETRANS-ORI-I", 14, 6, 0),
    BIT90_DHOTRANS_ORI_I(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "DHOTRANS-ORI-I", 15, 10, 0),
    BIT90_BIT032_ORI_I(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "BIT032-ORI-I", 16, 11, 0),
    BIT90_BIT033_ORI_I(BIT_090_ORIGINAL_DATA_ELEMENTS.getNumeroDaParte(), "BIT033-ORI-I", 17, 11, 0),

    BIT95_VLR_REAL_TXN(BIT_095_REPLACEMENT_AMOUNTS.getNumeroDaParte(), "VLR-REAL-TXN", 1, 12, 0),
    BIT95_VLR_REAL_LIQ(BIT_095_REPLACEMENT_AMOUNTS.getNumeroDaParte(), "VLR-REAL-LIQ", 2, 12, 0),
    BIT95_IND_TAX_TXN(BIT_095_REPLACEMENT_AMOUNTS.getNumeroDaParte(), "VLR-REAL-LIQ", 3, 1, 0),
    BIT95_VLR_REAL_TAX_TXN(BIT_095_REPLACEMENT_AMOUNTS.getNumeroDaParte(), "VLR-REAL-TAX-TXN", 4, 8, 0),
    BIT95_IND_TAX_LIQ(BIT_095_REPLACEMENT_AMOUNTS.getNumeroDaParte(), "IND-TAX-LIQ", 5, 1, 0),
    BIT95_VLR_REAL_TAX_LIQ(BIT_095_REPLACEMENT_AMOUNTS.getNumeroDaParte(), "VLR-REAL-TAX-LIQ", 6, 8, 0),

    BIT100_LONG_IDEN_INST_RECEP(BIT_100_BITMAP.getNumeroDaParte(), "LONG-IDEN-INST-RECEP", 1, 2, 0),
    BIT100_IDEN_INST_RECEP(BIT_100_BITMAP.getNumeroDaParte(), "IDEN-INST-RECEP", 2, 11, 0),

    BIT104_LONG_DADOS_SUBCREDEN(BIT_104_TRANSACTION_DESCRIPTION.getNumeroDaParte(), "LONG-DADOS-SUBCREDEN", 1, 3, 0),
    BIT104_DADOS_SUBCREDEN(BIT_104_TRANSACTION_DESCRIPTION.getNumeroDaParte(), "DADOS-SUBCREDEN", 2, 999, 0),
    BIT104_SUBCREDEN_ID(BIT_104_TRANSACTION_DESCRIPTION.getNumeroDaParte(), "SUBCREDEN-ID", 3, 11, 0),
    BIT104_SUBCREDEN_NUM_ID(BIT_104_TRANSACTION_DESCRIPTION.getNumeroDaParte(), "SUBCREDEN-NUM-ID", 4, 15, 0),
    BIT104_SUBCREDEN_NUM_ID2(BIT_104_TRANSACTION_DESCRIPTION.getNumeroDaParte(), "SUBCREDEN-NUM-ID2", 5, 15, 0),
    BIT104_SUBCREDEN_ID2(BIT_104_TRANSACTION_DESCRIPTION.getNumeroDaParte(), "SUBCREDEN-ID2", 6, 14, 0),

    BIT105_LONG_DADOS_ESPECIF2(BIT_105_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "LONG-DADOS-ESPECIF2", 1, 3, 0),
    BIT105_DADOS_ESPECIF2(BIT_105_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "DADOS-ESPECIF2", 2, 999, 0),

    BIT106_LONG_DADOS_TRANSACI(BIT_106_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "LONG-DADOS-TRANSACI", 1, 3, 0),
    BIT106_DADOS_TRANSACI(BIT_106_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "DADOS-TRANSACI", 2, 999, 0),

    BIT107_LONG_DADOS_TRNESP(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "LONG-DADOS-TRNESP", 1, 3, 0),
    BIT107_DADOS_TRNESP(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "DADOS-TRNESP", 2, 999, 0),
    BIT107_TRNESP_TIPPAG(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-TIPPAG", 3, 3, 0),
    BIT107_TRNESP_NUM_UNICO_REF(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-NUM-UNICO-REF", 4, 19, 0),
    BIT107_TRNESP_NOM_REM(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-NOM-REM", 5, 40, 0),
    BIT107_TRNESP_DIR_REM(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-DIR-REM", 6, 50, 0),
    BIT107_TRNESP_CID_REM(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-CID-REM", 7, 25, 0),
    BIT107_TRNESP_COD_PAIS(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-COD-PAIS", 8, 3, 0),
    BIT107_TRNESP_CEP_PORT(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-CEP-PORT", 9, 15, 0),
    BIT107_TRNESP_ID_PORT(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-ID-PORT", 10, 38, 0),
    BIT107_TRNESP_ORI_FONDOS(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-ORI-FONDOS", 11, 2, 0),
    BIT107_TRNESP_DATA_NACI_REM(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-DATA-NACI-REM", 12, 8, 0),
    BIT107_TRNESP_NOM_DEST(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-NOM-DEST", 13, 24, 0),
    BIT107_TRNESP_DAD_ADIC_TRANF(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-DAD-ADIC-TRANF", 14, 80, 0),
    BIT107_TRNESP_COD_DEST(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-COD-DEST", 15, 24, 0),
    BIT107_TRNESP_EMAIL_REM(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-EMAIL-REM", 16, 40, 0),
    BIT107_TRNESP_EMAIL_DEST(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-EMAIL-DEST", 17, 40, 0),
    BIT107_TRNESP_TLF_REM(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-TLF-REM", 18, 11, 0),
    BIT107_TRNESP_TLF_DEST(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-TLF-DEST", 19, 11, 0),
    BIT107_TRNESP_DEVICE_ID(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-DEVICE-ID", 20, 64, 0),
    BIT107_TRNESP_CPF_CNPJ_PORT(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-CPF-CNPJ-PORT", 21, 14, 0),
    BIT107_TRNESP_BIN_RETIRADA(BIT_107_RESERVED_FOR_ISO_USE.getNumeroDaParte(), "TRNESP-BIN-RETIRADA", 22, 8, 0),

    BIT121_BLOCO_2_PIN(BIT_121_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "BLOCO-2-PIN", 1, 8, 0),

    BIT122_LONG_DADOS_ADIAUTET(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "LONG-DADOS-ADIAUTET", 1, 3, 0),
    BIT122_DADOS_ADIAUTET(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADIAUTET", 2, 100, 0),
    BIT122_DADOS_ADI_AUT_TIP_AUT(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-TIP-AUT", 3, 2, 0),
    BIT122_DADOS_ADI_AUT_RES_AUT(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-RES-AUT", 4, 2, 0),
    BIT122_DADOS_ADI_AUT_SEG_FAT(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-SEG-FAT", 5, 2, 0),
    BIT122_DADOS_ADI_AUT_IND_CHAV(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-IND-CHAV", 6, 2,
	    0),
    BIT122_DADOS_ADI_AUT_VAL_CAVV(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-VAL-CAVV", 7, 4,
	    0),
    BIT122_DADOS_ADI_AUT_NUM_IMPR(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-NUM-IMPR", 8, 4,
	    0),
    BIT122_DADOS_ADI_AUT_RAST_AUT(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-RAST-AUT", 9, 16,
	    0),
    BIT122_DADOS_ADI_AUT_VER_ACAO(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-VER-ACAO", 10, 1,
	    0),
    BIT122_DADOS_ADI_AUT_ACAO_AUT(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-ACAO-AUT", 11, 1,
	    0),
    BIT122_DADOS_ADI_AUT_END_IP(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-ADI-AUT-END-IP", 12, 8, 0),
    BIT122_FILLER(BIT_122_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "BIT122-FILLER", 13, 58, 0),

    BIT123_LONG_CAMPO_PROMOCIO(BIT_123_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "LONG-CAMPO-PROMOCIO", 1, 3, 0),
    BIT123_CAMPO_PROMOCIO(BIT_123_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "CAMPO-PROMOCIO", 2, 999, 0),

    BIT124_LONG_QUAL_TRAN(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "LONG-QUAL-TRAN", 1, 3, 0),
    BIT124_QUAL_TRAN(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "QUAL-TRAN", 2, 124, 0),
    BIT124_B124_TRILHA1(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-TRILHA1", 3, 1, 0),
    BIT124_B124_TRILHA2(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-TRILHA2", 4, 1, 0),
    BIT124_B124_COND_DADOS_TRX(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-COND-DADOS-TRX", 5, 2, 0),
    BIT124_B124_PRODCAR(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-PRODCAR", 6, 1, 0),
    BIT124_B124_INDPARCHIP(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-INDPARCHIP", 7, 1, 0),
    BIT124_B124_BIT55(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-BIT55", 8, 1, 0),
    BIT124_B124_HOSTCAPT(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-HOSTCAPT", 9, 1, 0),
    BIT124_B124_SCORFRAU(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-SCORFRAU", 10, 3, 0),
    BIT124_B124_DADOSFRAU1(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOSFRAU1", 11, 20, 0),
    BIT124_B124_DADOSFRAU2(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOSFRAU2", 12, 20, 0),
    BIT124_B124_DADOSFRAU3(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOSFRAU3", 13, 20, 0),
    BIT124_B124_DADOSFRAU4(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOSFRAU4", 14, 20, 0),
    BIT124_B124_SCO_FRAU_CREDEN(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-SCO-FRAU-CREDEN", 15, 4, 0),
    BIT124_B124_SCO_FRAU_ELO(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-SCO-FRAU-ELO", 16, 4, 0),
    BIT124_B124_MOT_PRI_SCO_FRA(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-MOT-PRI-SCO-FRA", 17, 2, 0),
    BIT124_B124_MOT_SEC_SCO_FRA(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-MOT-SEC-SCO-FRA", 18, 2, 0),
    BIT124_B124_MOT_TER_SCO_FRA(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-MOT-TER-SCO-FRA", 19, 2, 0),
    BIT124_B124_REC_DECIS_FRAUD(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-REC-DECIS-FRAUD", 20, 1, 0),
    BIT124_B124_IND_ORI_SCORE(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-IND-ORI-SCORE", 21, 1, 0),
    BIT124_B124_USO_FUTURO(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-USO-FUTURO", 22, 67, 0),
    BIT124_B124_APROVJOGO(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-APROVJOGO", 23, 1, 0),
    BIT124_B124_PRODCAR_CRED(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-PRODCAR-CRED", 24, 1, 0),
    BIT124_B124_DATA_COMPR(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DATA-COMPR", 25, 6, 0),
    BIT124_B124_NUM_VIOLA(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-NUM-VIOLA", 26, 2, 0),
    BIT124_B124_DADOS_TRLH(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOS-TRLH", 27, 1, 0),
    BIT124_B124_DADOS_CVE(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOS-CVE", 28, 1, 0),
    BIT124_B124_DADOS_PAN(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DADOS-PAN", 29, 1, 0),
    BIT124_B124_DATA_VENC(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-DATA-VENC", 30, 1, 0),
    BIT124_B124_NOM_PORT(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-NOM-PORT", 31, 1, 0),
    BIT124_B124_END_PORT(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-END-PORT", 32, 1, 0),
    BIT124_B124_PIN(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "B124-PIN", 33, 1, 0),
    BIT124_IND_COMP_DCA(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-DCA", 34, 3, 0),
    BIT124_IND_COMP_TR1(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-TR1", 35, 1, 0),
    BIT124_IND_COMP_PAIS(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-PAIS", 36, 3, 0),
    BIT124_IND_COMP_TR2(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-TR2", 37, 1, 0),
    BIT124_IND_COMP_ANO(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-ANO", 38, 4, 0),
    BIT124_IND_COMP_TR3(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-TR3", 39, 1, 0),
    BIT124_IND_COMP_CASO(BIT_124_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "IND-COMP-CASO", 39, 5, 0),

    BIT125_LONG_USO_PERSONAL(BIT_125_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "LONG-USO-PERSONAL", 1, 3, 0),
    BIT125_DADOS_USO_PERSONAL(BIT_125_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-USO-PERSONAL", 2, 999, 0),

    BIT126_LONG_IDEN_CARTAOCVE2(BIT_126_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "LONG-IDEN-CARTAOCVE2", 1, 3, 0),
    BIT126_DADOS_IDEN_CARTCVE2(BIT_126_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-IDEN-CARTCVE2", 2, 999, 0),
    BIT126_CARTCVE2_INFO(BIT_126_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-IDEN-CARTCVE2", 3, 1, 0),
    BIT126_CARTCVE2_DADO(BIT_126_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "CARTCVE2-DADO", 4, 1, 0),

    BIT127_LONG_IDEN_VERSAO(BIT_127_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "LONG-IDEN-VERSAO", 1, 1, 0),
    BIT127_DADOS_IDEN_VERSAO(BIT_127_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "DADOS-IDEN-VERSAO", 2, 999, 0),
    BIT127_VERSAO_ISO(BIT_127_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "VERSAO-ISO", 3, 2, 0),
    BIT127_VERSAO_ANO(BIT_127_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "VERSAO-ANO", 4, 2, 0),
    BIT127_VERSAO_NUM(BIT_127_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "VERSAO-NUM", 5, 1, 0),
    BIT127_FILLER(BIT_127_RESERVED_FOR_PRIVATE_USE.getNumeroDaParte(), "BIT127-FILLER", 6, 994, 0);

    /**
     * Representa a numeracao de ordem do campo. Ex: Campo 1, Campo 2... Campo 127.
     */
    public int numeroDeOrdemDaParteDaMensagemCobol;
    public String nomeDoAtributo;
    /**
     * Representa a numeracao de ordem do atributo dentro de um campo. Ex: No Campo
     * 53, temos: Atributo 1= nomeDoEstabelecimento; Atributo 2= nomeDaCidade;
     * Atributo 3= codigoDoPAisOuEstado;
     */
    public int ordemDoAtributo;
    public int tamanhoDoAtributo;
    /**
     * Informacoes podem ser distanciadas por trails, desta maneira cada atributo
     * deve informar qual o espacamento entre ele e a proxima informação.
     */
    public int tamanhoASerIgnoradoPosLeituraDoAtributo;

    public static List<DeParaCOBOLCopybookCampoElo> buscarAtributosPorNumeroDaParteDaMensagemCobol(
	    ParteMensagemCOBOL parteDaMensagemCobol) {
	return Arrays.stream(DeParaCOBOLCopybookCampoElo.values()).filter(
		entrada -> entrada.numeroDeOrdemDaParteDaMensagemCobol == parteDaMensagemCobol.getNumeroDaParte())
		.collect(Collectors.toList());
}

}